config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'}, 
              :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
              
  get 'pages/about'
  get '/myprojects' => 'project#list'
  get 'application/download'
  post '/free' => 'charge#free'
  post '/pay' => 'charge#pay'
  
  root 'project#index'

  resources :project do 
    resources :task, only: [:show]
  end

  resources :project do 
    resources :reviews, only: [:create, :destroy]
  end

end

app/views/shares/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type= "text/javascript">
	<% resource.errors.full_messages.each do |msg| %>
		toastr.error('<%= msg %>')
	<% end %>
	</script>
<% end %>

app/views/shares/_footer.html.erb
<footer class="page-footer blue-grey darken-3">
	  <div class="container">
	    <div class="row valign-wrapper">
	      <div class="col l5 s12">
	      	<br/>
	        <h5 class="white-text">Carol Louie</h5>
	        <p class="grey-text text-lighten-4">I am an avid traveller. I love the challenges of learning; embracing a new culture, language or skill. Over the last year, I have been learning how to code in an immersion program <a href="http://www.uitstartup.org/">UIT</a>, where I acquired and developed the work habits and skills to develop a product from ideation and client discovery, to execution, testing and release. <%= link_to "Read more about me...", pages_about_path, :class => "red-text text-lighten-3" %> </p>
	      </div>
	      <div class="col l4 offset-l2 s12">
	      	<br/>
	        <h5 class="white-text">Find out more about me here:</h5><br/>
	        	<div class="row valign-wrapper">
	        		<%= link_to application_download_url do %>
	        		<%= image_tag "resumef.png", class:"circle responsive-img" %>
  					<% end %>&nbsp;&nbsp;&nbsp;&nbsp;
	        		
					 <a href="https://www.github.com/clouie87" target="_blank"> <%= image_tag "githubf.png", class:"circle responsive-img" %></a>&nbsp;&nbsp;&nbsp;&nbsp; 
					 <a href="https://ca.linkedin.com/pub/carol-louie/87/995/762" target="_blank"><%= image_tag "linkedinf.png", class:"circle responsive-img" %></a>&nbsp;&nbsp;&nbsp;&nbsp;
					 <a href="http://uitblog.com/" target="_blank"><%= image_tag "blogf.png", class:"circle responsive-img" %></a>&nbsp;&nbsp;&nbsp;&nbsp;
					 <a href="https://twitter.com/caroline_louie" target="_blank"><%= image_tag "twitter.png", class:"responsive-img footer-image"  %></a>&nbsp;&nbsp;&nbsp;&nbsp;
	        	</div>
	        </div>
	      </div>
	    </div>
	  </div>
	  <div class="footer-copyright">
	    <div class="container">
	    © 2015 Copyright Clouie
	
	    </div>
	  </div>
</footer>

app/views/shares/_header.html.erb
<header>
	<!-- Dropdown for Nav bar -->
	<ul id="dropdown1" class="dropdown-content mask">
	  <li><%= link_to "My Profile", edit_user_registration_path %></li>

	  <li><%= link_to "My Projects", myprojects_path %></li>
	 
	  <li class="divider"></li>
	  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	</ul>
	<!-- we create two one for mobile and one for web -->
	<ul id="dropdown2" class="dropdown-content mask">
	  <li><%= link_to "My Profile", edit_user_registration_path %></li>
	  <li><%= link_to "My Projects", myprojects_path %></li>
	  <li class="divider"></li>
	  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
	</ul>

	<nav class="blue-grey darken-3 z-depth-2">
		<div class="container" >
			<div class="nav-wrapper">
		      <a href="#!" class="brand-logo">Carol's Tech</a>
		      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
	
		      <ul class="right hide-on-med-and-down">
		        <li style="font-size: 24pt"><%= link_to "Projects", root_path %></li>
		        <li><%= link_to "About me", pages_about_path %></li>
		        <% if(!user_signed_in?) %>
		        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
		        	<li><%= link_to "Login", new_user_session_path %></li>
		       	<% else %>
		        	<li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown1">
		        		<%= image_tag avatar_url(current_user), class: "circle responsive-image avatar-small" %>&nbsp;
		        		<%= current_user.email %><i class="mdi-navigation-arrow-drop-down right"></i></a>
		        	</li>
	        	<% end %>
	        	<li><a href="http://uitblog.com/"> Blog</a></li>	
		      </ul>
		      <ul class="side-nav" id="mobile-demo">
		        <li><a href="#">Projects</a></li>
		        <li><%= link_to "About me", pages_about_path %></li>
		        <% if(!user_signed_in?) %>
		        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
		        	<li><%= link_to "Login", new_user_session_path %></li>
		       	<% else %>
		        	<li><a class="dropdown-button valign-wrapper" href="#!" data-activates="dropdown2">
		        		<%= image_tag avatar_url(current_user), class: "circle responsive-image avatar-small" %> &nbsp;

		        		<%= current_user.email %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
	        	<% end %>
		      </ul>
		    </div>
		</div>
		
		</nav>
</header>

app/views/shares/_message.html.erb
<% unless flash.empty? %>
	<script type= "text/javascript">
	<% flash.each do |f| %>
		<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
		toastr['<%= type %>']('<%= f[1] %>')
	<% end %>
	</script>
<% end %>